### ISSUE TITLE
Increment.

### ISSUE THREAD

**Issue by huandney** [p4nix/add-card-do-first-review#2]
Hi,
You could add a function to choose the time interval for the first review, regardless of the deck settings.
Thanks.

**Comment by p4nix** [comment]
Oops, somehow I missed your comment. Sorry!

I am not sure if this would be the most clever way to go about things. Most easiest solution would obviously just be adding a small option for a static interval. However, this would apply to all decks then, which could be a bit annoying. The current solution is plain and simple, and accounts for the use case I have in mind for the add-on.

Perhaps you could elaborate a bit on the idea, and how implementation could look like?

**Comment by huandney** [comment]
> Oops, somehow I missed your comment. Sorry!
> 
> I am not sure if this would be the most clever way to go about things. Most easiest solution would obviously just be adding a small option for a static interval. However, this would apply to all decks then, which could be a bit annoying. The current solution is plain and simple, and accounts for the use case I have in mind for the add-on.
> 
> Perhaps you could elaborate a bit on the idea, and how implementation could look like?

Hi,
So, it's because I have two different deck configurations:
1st Deck (lapses steps): 2 20 1440 8640
2nd Deck (lapses steps): 15 1440 8640

I use different settings, because in the first deck the cards are mostly not made by me, so I added one more step (to better retain the information).

But sometimes I add cards, so I wanted it to appear to me only after 1440 minutes, that is 1 day and not after 20 minutes.
